export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const LOGUSER_SUCCESS = 'LOGUSER_SUCCESS';
export const LOGUSER_ERROR = 'LOGUSER_ERROR';
export const LOGUSER_REQUEST = 'LOGUSER_REQUEST';

export const UPDATE_CREDS = 'UPDATE_CREDS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
