export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const LOGUSER_SUCCESS = 'LOGUSER_SUCCESS';
export const LOGUSER_ERROR = 'LOGUSER_ERROR';
export const LOGUSER_REQUEST = 'LOGUSER_REQUEST';
export const LOGOUTUSER = 'LOGOUTUSER';

export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_ERROR = 'GET_ROOM_ERROR';

export const GET_ROOMLIST_SUCCESS = 'GET_ROOMLIST_SUCCESS';
export const GET_ROOMLIST_ERROR = 'GET_ROOMLIST_ERROR';

export const REGUSER_SUCCESS = 'REGUSER_SUCCESS';
export const REGUSER_ERROR = 'REGUSER_ERROR';
export const REGUSER_REQUEST = 'REGUSER_REQUEST';

export const RESET_ERR = 'RESET_ERR';
